# Este é um arquivo de configuração
# aqui devemos descrever e definir as 
# gatilhos, etapas, versões e comandos
# que essa maquina/boro deve executar

# Nome do nosso teste
name: Python application test

on: # Quando o evento deve executar

jobs: # Construção passo a passo da sua tarefa
  build: # Etapa de construção/criação

    runs-on: ubuntu-latest # Em qual plataforma vai rodar

    steps: # Passo a passo da etapa de build
    - uses: actions # Definição da ação do GitHub, exemplo actions/merge@v2, funciona como uma biblioteca
    
    - name: Setup Python version
      uses: actions # Novamente escolher uma lib de ação
      with:
        python-version: '3.*'

    - name: 

    - name: Run test # name define o nome de uma seção no passo a passo, nesse caso é a ultima etapa, rodar testes
      run: python -m unittest discover -s . # Comando que deve ser executado na máquina/robo que nosso arquivo montou